feat: initial release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,5 +1,4 @@
 name: Release and Push Docker Image
-
 on:
   push:
     branches:
@@ -15,18 +14,18 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      
+
       - name: Set up Node.js 22
         uses: actions/setup-node@v4
         with:
           node-version: 22
-      
+
       - name: Install Dependencies
         run: npm ci
-      
+
       - name: Set execute permission for semantic-release
         run: chmod +x node_modules/.bin/semantic-release
-      
+
       - name: Run Semantic Release
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
@@ -38,22 +37,31 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
-      
+        with:
+          fetch-depth: 0
+
+      - name: Debug - List Files
+        run: ls -la
+
+      - name: Debug - Check package.json
+        run: cat package.json || echo "package.json not found!"
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-      
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-      
+
       - name: Extract Version from Package.json
         id: get_version
         run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
-      
+
       - name: Build and Push Docker Image
         run: |
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ env.VERSION }} -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest .
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ env.VERSION }} \
+                       -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest -f ./Dockerfile .
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ env.VERSION }}
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
